version: '3.5'

services:
  db:
    image: postgres:16-alpine
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=service
